//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVEHIST
    {
        public long MOVEHIST_ID { get; set; }
        public long lineno { get; set; }
        public string TYPE { get; set; }
        public string OLD_DATA { get; set; }
        public string NEW_DATA { get; set; }
        public string OLD_SAL { get; set; }
        public string NEW_SAL { get; set; }
        public string D_ACTION { get; set; }
        public string T_ACTION { get; set; }
        public string DESCRIPTION { get; set; }
        public string ACTION_BY { get; set; }
        public string Id { get; set; }
    }
}
